name: dockerfiles

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: "0 0 1 * *"
  pull_request:
  push:
    branches:
      - main
    paths:
      - "**Dockerfile"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        docker_image:
          - "eloquent_msgs"
          - "joy"
          - "ros1_bridge"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Update date
        run: |
          echo "TODAY=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ${{ matrix.docker_image }}
          file: ./${{ matrix.docker_image }}/Dockerfile
          tags: athackst/deepracer:${{ matrix.docker_image }},athackst/deepracer:${{ matrix.docker_image }}-${{ env.TODAY }}
          push: github.ref == 'refs/heads/main'
  readme:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Update repo description
        uses: peter-evans/dockerhub-description@v2.4.2
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKERHUB_REPOSITORY: athackst/deepracer
